### ISSUE TITLE
overlapping patterns in 'with' and 'orwith'

### ISSUE THREAD

**Issue by lutzhamel** [lutzhamel/asteroid#17]
If you have overlapping patterns in the 'with' or 'orwith' clauses of a function definition and the patterns are not order from the most specific to the most general pattern matching will lead to unexpected results. Consider,

```
load "io".

class A with

    data x.
    data y.

    function __init__
      with self do
        let self@x = 1.
        let self@y = 2.
      orwith self, a, b do
        let self@x = a.
        let self@y = b.
      end function
    end class

let obj1 = A("hello","world").
print obj1.
let obj2 = A(none).
print obj2.
```
In the function __init__ the first pattern is more general than the second and will match anything that the constructor is called with.  This leads to unexpected results.

The current work around is to make sure that your with clauses are order from the most specific to the most general.

**Comment by TimColaneri** [comment]
This issue has been resolved, with a single reservation detailed at the bottom.

A redundant pattern detection function has been added to the Asteroid interpreter to allow for detection of redundant/useless patterns within a function's 'with/orwith' clauses. This function evaluates every pattern found within a function's clauses and compares each of these patterns to the patterns that are found in the following 'orwith' clauses. The comparison made here evaluates the subsumption relationship between the two patterns. If the preceding pattern is found to subsume the following pattern, then a redundant/useless pattern has been found.

The subsumption evaluation is done through the preexisting 'unify' function, which handles pattern-matching in the Asteroid Interpreter. This evaluation essentially determines if the two different patterns could be "mapped" together.

When a redundant/useless pattern has been found, an error is generated, the interpreter is halted, and a message is printed to the console.

NOTE: It was determined during development of the redundant pattern detector that conditional patterns in a 'with/orwith' function clause may be unable to be evaluated until it is actually interpreted. As such, it cannot be determined if a conditional pattern renders a following 'orwith' clause's pattern to be redundant/useless. The current behavior of the redundant pattern detector when recognizing multiple conditional patterns in a function's 'with/orwith' clauses is to print a warning message to the console, after which the Asteroid Interpreter will continue with interpretation.

**Comment by CalinZBaenen** [comment]
To: @lutzhamel, @TimColaneri

I know I'm late, and I don't know what this pattern in, but I've been trying to get the word I recently coined onto the top ov search engines and code with `orwith` or `::orWith` in it is impairing my progress.  
So, as not to confuse any non-programmers or programmers who learn the word I coined, does the keyword `orwith` mean the same thing as (or similar to) ["orwith", the word I recently coined](https://www.deviantart.com/kattytheenby/journal/Def-Orwith-950684792)?
> \[Conjunction\]  
> 1. Being accompanied by, or outright replaced with, something; __and/or__.  
> 2. Indicating both options are, or can be, possibilities; __"or with"__.

**Comment by lutzhamel** [comment]
This is now an obsolete keyword in Asteroid and will no longer supported in future versions of Asteroid.

As to your question, `with` is a keyword in Asteroid that has an "inclusion meaning" stating that a particular feature is defined "with" some set of characteristics.  Under certain circumstances it is possible to have a disjunction of definition and that is precisely what the `orwith` keyword implied.  However, from a programming language perspective this was kind of clunky and we dropped it.

**Comment by CalinZBaenen** [comment]
> Under certain circumstances it is possible to have a disjunction of definitions and that is precisely what the orwith keyword implied.

So is that alike to what my word means? It does sound like it, but instead ov jumping from "or" to "and/or", we're jumping from "and" (`with`\*) to "and/or".

(BTW, what do you think ov my word, @lutzhamel?)
