### ISSUE TITLE
Tuples are not correctly passed to member functions

### ISSUE THREAD

**Issue by olwmc** [lutzhamel/asteroid#56]
Tuples don't correctly get passed as arguments to member functions.

## Example 1:

```
load "io".

let entries = [(1,2), (3,4),(5,6)].

function foo
	with (x,y) do
		return (y,x).
		end

println(foo(entries @0)).   -- This works fine.
println(entries @map(foo)). -- This crashes
```

## Example 2:
```
load "io".

let array = [1,2,3].

array @extend((4,5,6)). -- This crashes
println(array).
```

## Discussion
This is seemingly because on line `1066` in `asteroid_walk.py`, when a member function *has* a tuple as an argument, it inserts the object reference at the beginning of the tuple like:

`arg_val[1].insert(0, obj_ref)`

That being said, though, changing this would clash with the way tuples are passed into `hash.ast`'s `insert` function.

```
function insert
with (self,name,value) do escape
```

As we can see, insert expects a tuple with the self reference at the beginning, something in the form `(self, "today", "tuesday")` and not `(self, ("today", "tuesday"))`.

The question now becomes do we want tuples to be passed like `(self, (x,y,z)) ` **OR** `(self, x,y,z)`. To me, the first option makes more intuitive sense. When you pass a tuple, you will be looking to pattern match a tuple, not individual arguments.

I have a fix lined up which not only resolves the issue but also converts the old libraries which used the old syntax to the new one.

### What do you folks think?

**Comment by olwmc** [comment]
Currently if you want to pattern match against a 2-tuple being passed to a member function, you do:
```
function func
    with (self, x,y) do
        return true.
        end

object @func(1,2).
```
(An example of this can be seen in the `__list_insert__` method).

With my change, which I believe is more accurate, the previous example would be changed to:
```
function func
    with (self, (x,y)) do
        return true.
        end

object @func(1,2).
```

**Comment by lutzhamel** [comment]
Let's take a look at function calls in Asteroid,  `foo none` is call with no parameters and is equivalent to a call with an empty tuple, `foo ()`.  In Asteroid a call with multiple parameters is always a call with a tuple as a parameter, `foo (1,2)` is a call with the tuple `(1,2)` as its single argument.  This is very different to Python, see below,
```
class Foo:
    def f(self,x):
        print(x)

o = Foo()
o.f((1,2)) # in Python we have to use double parentheses to indicate that we want to pass a tuple
```
Your proposed solution works well if there is a tuple as a parameter. So how does your proposed solution work with empty tuples as arguments? By extension of your proposed solution it would be something like this,
```
function f with (self,()) do .... end
```
That seems counter intuitive.  If we can solve this then I think this would work and we should adopt it.

**Comment by lutzhamel** [comment]
I was just thinking, perhaps the Python object reference model for member functions is the wrong model for us.  May be we should adopt the C++/Java object reference model where the original argument list appears untouched to the user and the object reference is mapped to a reserved variable `this`.  In this case, Oliver's proposal would work nicely under the hood and at member function execution time the original argument list is exposed for pattern matching and the object reference is mapped to `this` implicitly,
```
structure Foo with 
   data m.
   function __init__ with s do
        let this @m = s.
        end
   function f with none do
        println (this @m).
        end
  end
```

**Comment by olwmc** [comment]
I like the implicit `this` as opposed to the current syntax. It feels like a good compromise between the paradigm clashes. I changed the issue type to `research` as this is a change which will probably require further exploration.

**Comment by lutzhamel** [comment]
Implemented the 'this' model of object reference in member function.  Also implemented error checking in the sense that if you try to declare a variable called 'this' it will be rejected. Adjusted all modules, test suites, and doc files. Added additional regression tests based on the programs reported not working above.
