### ISSUE TITLE
Bitwise Operations

### ISSUE THREAD

**Issue by TimColaneri** [lutzhamel/asteroid#62]
Currently, Asteroid has no means of evaluating [bitwise operations](https://en.wikipedia.org/wiki/Bitwise_operation).

Should these operations be implemented as built-in expressions?
`let x = 1 << 2.`
`assert(x == 4).`
Or as a module?
`load "bitwise".`
`let x = left_shift(1,2).`
`assert(x == 4).`

**Comment by olwmc** [comment]
I really like the module option. It not only keeps the syntax smaller but also feels like a good use of the module/escape system. Why add a whole new set of operators when you can write a simple module? Moreover, at this high of a level of abstraction (to me, at least) it feels like bitwise operations would be comparatively rare, thus really diminishing the utility of having them as a specific operator. Additionally, we sort of set a precedent with not including `%` for modulo, so it feels natural to just take advantage of a module for this task.

**Comment by lutzhamel** [comment]
Nice assessment!  I probably would have argued in a similar way.

**Comment by olwmc** [comment]
Closed with #71

**Comment by olwmc** [comment]
Closed with #71
