### ISSUE TITLE
Asteroid exceptions and the try/catch statement.

### ISSUE THREAD

**Issue by TimColaneri** [lutzhamel/asteroid#64]
All Python exceptions within the Asteroid interpreter are currently mapped to the generic "Exception" Asteroid exception. Asteroid only has one type of internal exception sub-type that is currently exposed, the "PatternMatchFailed" exception. 

It is a consequence of this that a developer using Asteroid will only have one type of exception, beyond the generic exception, that they can write a catch clause for in a try/catch statement.

**The primary question here is:** Should we map all Python exceptions into the generic exception? Or should we expose more specific exception types? 

The complication here being that Asteroid has no knowledge of the Python exception hierarchy.

**Comment by lutzhamel** [comment]
@TimColaneri , @olwmc, I would be interested to hear your thoughts on the proposal for exceptions below.

Exceptions in Asteroid can take three different forms:

1. A user generated Asteroid exception using the Error type defined in the Prologue and using the `throw` keyword.
2. A user generated Asteroid exception using a user defined data structure and using the `throw` keyword.
3. A system generated exception which is a Python exception.  Currently we map all Python exceptions except the "PatternMatchFailed" exception into a 2-tuple where the first component has the string 'Exception' and the second component is a string detailing the exception.  The "PatternMatchFailed" exception gets mapped into the 2-tuple ("PatternMatchFailed", <detail string>).

Of course Asteroid allows you to throw any kind of data structure as an exception, however, here we are talking only about the exceptions provided by Asteroid and the underlying system

The current approach is very confusing and very difficult to explain.  To high-light the situation, here is an example program (based on Tim's original example) 
```
load system "io".
load system "util".

println
"\n
1 - forces a pattern match exception\n
2 - forces a user exception\n
3 - forces a system exception\n".

let i = tointeger(input("Enter an option: ")).

if i == 1 do
   let q = (1,2,3).  -- this forces a pattern match exception
elif i == 2 do
   let q = (1,2).    -- this forces a user exception
elif i == 3 do
   let q = (2,2).    -- this forces a system exception
else do
   exit ("unknown option: "+i).
end

try
    let (x,y) = q.
    if x == 1 do
       throw Error("x == 1").
     elif y == 2 do
       println(y/0).
     end
catch ("PatternMatchFailed",s) do        -- pattern match exception
    println("Pattern match failed: "+s).
catch Error(s) do                        -- user exception
    println("User Exception: "+s).
catch ("Exception",s) do                 -- system exception
    println("Exception: "+s).
end.
```
You can probably see the problem, every category of exception looks different and needs to be matched/handled differently.

Here is a proposal to make all exception look the same.  In this case the try-catch block from above would look something like this,
```
...
try
    let (x,y) = q.
    if x == 1 do
       throw Exception("x == 1").  -- throwing an exception rather than error
     elif y == 2 do
       println(y/0).
     end
catch Exception(s) do    -- all exceptions are mapped into the Exception type
    println("exception: "+s).
end.
```
We can use pattern matching on the description string `s` to attach specific behavior to specific exceptions
```
...
try
    let (x,y) = q.
    if x == 1 do
       throw Exception("x == 1").  -- throwing an exception rather than error
     elif y == 2 do
       println(y/0).
     end
catch Exception(s) %if s is ".*pattern.*" do     -- handle pattern match exceptions
    println("pattern matching exception: "+s).
catch Exception(s) do    -- everything else
    println("exception: "+s).
end.
```

**Comment by olwmc** [comment]
> We can use pattern matching on the description string s to attach specific behavior to specific exceptions

I like this idea, it's a pretty good way of using pattern matching in an effective way with exceptions. I wonder, though, if we should keep the type of error and the description of the error separate. Something in the form `Exception(t,s) -- Type, description`.

The reason I think this distinction is useful is that it decreases the chance of a situation where, for example, the user throws an error containing the word *"pattern"*. Doing `catch Exception(s) %if s is ".*pattern.*"` would catch it as a `pattern match exception` as opposed to a `user exception`.

Something like `catch Exception(t, s) %if t is ".*pattern.*"` might be a slightly clearer way of distinguishing between error types.

I'm not super familiar with how exceptions are constructed, so I'll have to look into that to see if splitting it into a type and description is viable.

**Comment by lutzhamel** [comment]
I thought about this but then Python exceptions will become visible again and we have to come up with a type string for each of the Python exceptions and there are a lot of them:
https://docs.python.org/3/library/exceptions.html

Plus we would then need to track this carefully because this might change from Python release to Python release....

So, I'm not quite sure, can we generate that type string automatically for Python exceptions?

**Comment by TimColaneri** [comment]
If all exceptions are caught by something like...
`catch Exception(s) %if s is ".*pattern.*" do`

Could user-defined exceptions cause issues here? Would it be up to the developer defining a new exception type to ensure that it does not trigger on the patterns of other exceptions?

**Comment by lutzhamel** [comment]
It took me a while, but I finally figured out one of the sources of confusion: In Python when we do not care about the specific exception to be caught we specify the exception base class.  For example,
```
try:
    (x,y) = (1,2,3)
except Exception as e:
    print("error: {}".format(e))
```
Asteroid exceptions do not have base classes, they are simply objects that you can pattern match against.  So, in Asteroid, if you don't care about the specific exception type to be caught, you need to use wildcard patterns on the `kind` field of the exception,
```
load system "io".

try
  let (x,y) = (1,2,3).
catch (_,s) do
  println("error: "+s).
end
```
This still leaves the problem that we have three different kinds of exceptions in Asteroid that all look a little bit different. So here is a proposal that addresses that.

The proposal is that all standard Asteroid exceptions are mapped into an `Exception` object,
```
structure Exception with
    data kind.
    data val.
    function __init__
        with (kind:%string,val) do
            let this @kind = kind.
            let this @val = val.
        orwith val do
            let this @kind = "UserException".
            let this @val = val.
        end
    end
```
By default the object constructs a `UserException`.

Here are the different kinds of exceptions I envision.  This is mostly driven by the exception class hierarchy given at the bottom of this page: https://docs.python.org/3/library/exceptions.html

UserException               -- anything the user wants to throw
PatternMatchFailed
ArithmeticError              -- e.g. division by zero
FileNotFound                 -- encodes the Python FileNotFoundError exception
SystemException           -- everything else

These are strings that go into the `kind` field of the `Exception` object.  Notice that I specifically stayed away from the generic "Exception" kind in order to avoid confusion with the Python base class.

So the above Asteroid example could be rewritten with the new exceptions as follows,
```
load system "io".

try
  let (x,y) = (1,2,3).
catch Exception("PatternMatchFailed",_) do
   println("error: pattern match failed").
catch Exception(_,s) do
  println("error: "+s).
end
```
Here is an example using user defined exceptions,
```
load system "io".

try
   throw Exception("Hello World!").
catch Exception("UserException",s) do  -- the exception from previous line will match this
   println(s).
catch Exception(_,s) do
   println("error: "+s).
end
```
Let me know your thoughts.  Any additional exception kinds?

**Comment by TimColaneri** [comment]
This is probably the way to go. This gives our different exceptions a similar look and feel.

My only reservation is would we be able to have multiple catch clauses for multiple user-defined exceptions? Suppose the developer only wanted to catch one type of a user-defined exception while having another thrown; would that be possible here?

Also, don't forget the "RedundantPatternFound" exception.

**Comment by lutzhamel** [comment]
> My only reservation is would we be able to have multiple catch clauses for multiple user-defined exceptions? Suppose the developer only wanted to catch one type of a user-defined exception while having another thrown; would that be possible here?

Good question.  If users have multiple 

> user exceptions with specific behavior they can override the default behavior of the `Exception` object. This example handles one user exception and all other exception but does not catch the other user exception,

```
load system "io".
load system "random".

try
   if random() < .5 do
      throw Exception("MyException1","Hello World!").
  else do
     throw Exception("MyException2","Hello there!").
  end
catch Exception("MyException1",s) do
   println("MyException1: "+s).
catch Exception(kind,s) %if kind =/= "MyException2" do
   println("error: "+s).
end
```

> Also, don't forget the "RedundantPatternFound" exception.

I will add that to the list above...

**Comment by lutzhamel** [comment]
@TimColaneri @olwmc, I have implemented the new exceptions based on the feedback above.  The basic idea is that we have user level exception based on `Error` objects,
```
------------------------------------------------------------------
structure Error
------------------------------------------------------------------
-- convenient user level exceptions
with
  data err_val.
  function __init__
    with val do
      let this @err_val = val.
    end
  end
```
that can be used as follows,
```
try
   throw Error("my user exception").
catch Error(s) do
   println s.
catch _ do
  println "something else happened".
end
```
And then we have Asteroid standard exceptions that use `Exception` objects,
```
------------------------------------------------------------------
structure Exception
------------------------------------------------------------------
-- asteroid's standard exception structure.
-- note: both the kind and the val fields have to be given
with
  data kind.
  data val.
  function __init__
    with (kind:%string,val) do
      let this @kind = kind.
      let this @val = val.
    end
  end
```
All Asteroid generated exceptions use `Exception` objects, e.g.
```
try
   let (x,y) = (1,2,3).
catch Exception("PatternMatchFailed",s) do
   println s.
catch Exception(_,s) do
  println ("some exception happened: "+s).
end
```
I'm still not 100% happy with user exceptions looking differently than Asteroid exceptions.  One thing I am thinking about is the `__str__` member function for structures which would behave very similar to the `__str__` function in Python and would allow us to write code as follows,
```
try 
   let (x,y) = (1,2,3).
catch e do
  println e.  -- automatic conversion of exception object to a string for printing
end
```
or something like this,
```
try 
   let (x,y) = (1,2,3).
catch e do
  println ("exception caught: "+tostring(e)).  -- explicit conversion of exception object to a string for printing
end
```
Hiding the precise structure of the exception.
That way, if you are not fuzzy about what precisely caused the exception the same code holds for user level exceptions assuming that the `Error` structure also has a `__str__` member function,
```
try 
   throw Error("my user exception").
catch e do
  println ("exception caught: "+tostring(e)).  -- explicit conversion of exception object to a string for printing
end
```
What do you think?

**Comment by TimColaneri** [comment]
Sorry for the delayed reply, I took some time to think about this.

> I'm still not 100% happy with user exceptions looking differently than Asteroid exceptions. 

I hear you on this. However, I don't think its awful to have two different flavors of exceptions in Asteroid. Given the current situation, I think this is a fine solution. 

I imagine that the __str__ functionality would be very useful by allowing a developer to easily print the contents on an unexpected exception in the console for the purpose of debugging. This also opens up the avenue of analysis by regular expressions.


Perhaps the actual exception patterns could be constant first-class patterns declared in one of the fundamental modules( 'io' or 'util'), in which case we could write something like...

`catch *USER_EXCEPTION do`
`catch *ASTEROID_EXCEPTION do`

I couldn't help but notice one of your examples contained a "conditional catch", we could potentially bring the functionality of conditional pattern matching to expand on this. 

`let MY_ERRORS_PATTERN = pattern with "^ERROR1".         -- Regular expression pattern`
`let CUSTOM_EXCEPTION = pattern with Error(s) %if s is *MY_ERRORS_PATTERN,`

So we could end up with a catch clause like...

`catch *CUSTOM_EXCEPTION do`

Just an idea...

**Comment by lutzhamel** [comment]
Nested first-class patterns! I love it!

BTW, in today's Asteroid any object (including user constructed one) can already be cast into a string,
```
load system "io".
load system "util".

structure Foo with
   data bar.
   end

let o = Foo("Hello there!").
println (tostring o).
```
The `__str__` function will allow you to customize the way objects are stringified.

**Comment by lutzhamel** [comment]
System exceptions are now visible to the user at the Asteroid level as `Exception` objects with the following structure,
```
structure Exception with
   data kind.
   data value.
   end
```
The `kind` field will be populated with one of the following strings,

* `PatternMatchFailed`
* `RedundantPatternFound`
* `ArithmeticError` -- e.g. division by zero
* `FileNotFound` -- encodes the Python FileNotFoundError exception
* `SystemError` -- everything else raised by Python

The `value` field holds a string with some exception details.
The exceptions can be caught as follows, *e.g.*
```
load system "io".

try
  let x = 1/0.
catch Exception("ArithmeticError", s) do
  println s.
end
```
The user is still allowed to construct user level exceptions with any kind of object including tuples and lists,
```
load system "io".

try
  throw ("funny exception", 42).
catch ("funny exception", v) do
  println v.
end
```
Asteroid provides a predefined `Error` object for user level exceptions,
```
load system "io".

try
  throw Error("something worth throwing").
catch Error(s) do
  println s.
end
```
If you don't care what kind of exception you catch you need to use a `wildcard` or a variable.  Here is an example using a `wildcard`,
```
load system "io".

try
  let (x,y) = (1,2,3).
catch _ do
  println "something happened".
end
```
Here is an example using a variable,
```
load system "io".
load system "util".

try
  let (x,y) = (1,2,3).
catch e do
  println ("something happened: "+tostring(e)).
end
```
