### ISSUE TITLE
The list member function pop() is not functioning correctly

### ISSUE THREAD

**Issue by TimColaneri** [lutzhamel/asteroid#77]
There is an issue with the list function pop().

Currently, the list member function pop will return a broken AST. The Asteroid interpreter will then raise an error when attempting to interpret a broken AST.

The pop() function will pass back an AST which has a leading 'list' tag, but does not have a list on the next level. 

The following programs both throw errors:
```
load system "io".
let x = [1,2,3,4,5,6].
let y = x@pop(0).
assert(y == 1).
```
```
load system "io".
let x = [1,2,3,4,5,6].
let y = x@pop(0).
assert(y@0 == 1).
```
The return statement currently reads: 
__retval__ = ('list', this_val[1].pop() )
I believe to fix this that the return statement should read either:
__retval__ = ('list', [ this_val[1].pop() ] )
or
__retval__ = this_val[1].pop()

**Comment by lutzhamel** [comment]
fixed this bug mapping Asteroid's pop right on top of Python's  pop.  We now properly return the value stored at the list.
