### ISSUE TITLE
improved load syntax

### ISSUE THREAD

**Issue by lutzhamel** [lutzhamel/asteroid#96]
In almost all cases when using the `load` statement we simply just refer to the module name rather than the path to the module.  To save the user from typing the quotes for just module names we can extend the syntax of the `load` statement as follows,
```
load system io. -- just module name, no quotes necessary

println "hello world!".
```
This should work for both system modules and user defined modules.  Now quotes are only necessary if the user wants to provide an explicit path to a particular module.

**Comment by SupurCalvinHiggins** [comment]
@lutzhamel What do you think about this change to the grammar?

```
// old
LOAD SYSTEM? STRING '.'?

// new
LOAD SYSTEM? (STRING | ID) '.'?
```

Then
```
load system io.
load system "io".
```
function as expected.

**Comment by lutzhamel** [comment]
@SupurCalvinHiggins Perfect! Thank you!  Please close this issue.  I have accepted your pull request.

**Comment by SupurCalvinHiggins** [comment]
@lutzhamel I forgot to link the pull request initially and now I cannot close the issue. You might have to do it manually. Apologies, I am rather new to Git.
